### ISSUE TITLE
For discussion -- tool to create independent disks

### ISSUE THREAD

**Issue by mikepea** [gds-operations/vcloud-launcher#76]
Hey there vcloud-tools chums :)

The code in PR https://github.com/gds-operations/vcloud-launcher/pull/75 deals just with attaching pre-existing Independent Disks to VMs.

I purposefully left out code to create Independent Disks, as currently vcloud-launch deals solely with vApps/VMs.

What I was wondering was, would you prefer a tool -- eg 'vcloud-disk-launcher' -- in a separate Git repo and Gem, or instead should we extend vcloud-launcher to handle creation of these disks too?

In the latter case, I'm thinking we extend the YAML by adding (eg):

```
independent_disks:
  - name: bobdisk-1
    size: 10GB
  - name: bobdisk-2
    size: 10GB

vapps:
  ... as usual
```

What do you think? I prefer the latter solution, as they are very closely related. However, vcloud-disk-launcher maps to the current model, a'la vcloud-net-launcher.
